/***********************************************************************
Vczh Library++ 3.0
Developer: Zihan Chen(vczh)
GacUI::Partial Classes

This file is generated by: Vczh GacUI Resource Code Generator
************************************************************************
DO NOT MODIFY
***********************************************************************/

#ifndef VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_PARTIAL_CLASSES
#define VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_PARTIAL_CLASSES

#include "..\..\..\Public\Source\GacUIReflection.h"

namespace helloworld
{
	class IViewModel;
	class SignUpWindow;

	class IViewModel : public virtual vl::reflection::IDescriptable, public vl::reflection::Description<IViewModel>
	{
	public:

		virtual vl::WString GetUserName() = 0;
		virtual void SetUserName(vl::WString value) = 0;

		virtual vl::WString GetUserNameError() = 0;
		vl::Event<void()> UserNameErrorChanged;

		virtual vl::WString GetPassword() = 0;
		virtual void SetPassword(vl::WString value) = 0;

		virtual vl::WString GetPasswordError() = 0;
		vl::Event<void()> PasswordErrorChanged;

		virtual bool Commit(bool signIn) = 0;
	};

	template<typename TImpl>
	class SignUpWindow_ : public vl::presentation::controls::GuiWindow, public vl::presentation::GuiInstancePartialClass<vl::presentation::controls::GuiWindow>, public vl::reflection::Description<TImpl>
	{
		friend struct vl::reflection::description::CustomTypeDescriptorSelector<TImpl>;
	private:
		Ptr<helloworld::IViewModel> ViewModel_;
	protected:
		vl::presentation::controls::GuiButton* buttonSignUp;
		vl::presentation::controls::GuiSinglelineTextBox* textBoxPassword;
		vl::presentation::controls::GuiSinglelineTextBox* textBoxUserName;

		void InitializeComponents(Ptr<helloworld::IViewModel> ViewModel)
		{
			ViewModel_ = ViewModel;
			if (InitializeFromResource())
			{
				GUI_INSTANCE_REFERENCE(buttonSignUp);
				GUI_INSTANCE_REFERENCE(textBoxPassword);
				GUI_INSTANCE_REFERENCE(textBoxUserName);
			}
			else
			{
				ViewModel_ = 0;
			}
		}
	public:
		SignUpWindow_()
			:vl::presentation::GuiInstancePartialClass<vl::presentation::controls::GuiWindow>(L"helloworld::SignUpWindow")
			,vl::presentation::controls::GuiWindow(vl::presentation::theme::GetCurrentTheme()->CreateWindowStyle())
			,buttonSignUp(0)
			,textBoxPassword(0)
			,textBoxUserName(0)
		{
		}

		Ptr<helloworld::IViewModel> GetViewModel()
		{
			return ViewModel_;
		}
	};

}
namespace vl
{
	namespace reflection
	{
		namespace description
		{
			DECL_TYPE_INFO(helloworld::IViewModel)
			DECL_TYPE_INFO(helloworld::SignUpWindow)

		}
	}
}
/*
SignUpWindow.h :
namespace helloworld
{
	class SignUpWindow : public helloworld::SignUpWindow_<helloworld::SignUpWindow>
	{
		friend class helloworld::SignUpWindow_<helloworld::SignUpWindow>;
		friend struct vl::reflection::description::CustomTypeDescriptorSelector<helloworld::SignUpWindow>;
	protected:

		// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)
		// #endregion CLASS_MEMBER_GUIEVENT_HANDLER
	public:
		SignUpWindow(Ptr<helloworld::IViewModel> ViewModel);
	};
}


SignUpWindow.cpp :
namespace helloworld
{
	// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)

	// #endregion CLASS_MEMBER_GUIEVENT_HANDLER

	SignUpWindow::SignUpWindow(Ptr<helloworld::IViewModel> ViewModel)
	{
		InitializeComponents(ViewModel);
	}
}


*/

#endif
