/***********************************************************************
Vczh Library++ 3.0
Developer: Zihan Chen(vczh)
GacUI::ButtonTemplate

This file is generated by: Vczh GacUI Resource Code Generator
***********************************************************************/

#ifndef VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_ButtonTemplate
#define VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_ButtonTemplate

#include "HelloWorldPartialClasses.h"

namespace demos
{
	class ButtonTemplate : public ButtonTemplate_<ButtonTemplate>
	{
		friend class ButtonTemplate_<ButtonTemplate>;
		friend struct vl::reflection::description::CustomTypeDescriptorSelector<ButtonTemplate>;
	protected:

		// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)
		// #endregion CLASS_MEMBER_GUIEVENT_HANDLER
	public:
		ButtonTemplate();
	};
}

#endif
