/***********************************************************************
Vczh Library++ 3.0
Developer: Zihan Chen(vczh)
GacUI::CheckBoxTemplate

This file is generated by: Vczh GacUI Resource Code Generator
***********************************************************************/

#ifndef VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_CheckBoxTemplate
#define VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_CheckBoxTemplate

#include "HelloWorldPartialClasses.h"

namespace demos
{
	class CheckBoxTemplate : public CheckBoxTemplate_<CheckBoxTemplate>
	{
		friend class CheckBoxTemplate_<CheckBoxTemplate>;
		friend struct vl::reflection::description::CustomTypeDescriptorSelector<CheckBoxTemplate>;
	protected:

		// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)
		// #endregion CLASS_MEMBER_GUIEVENT_HANDLER
	public:
		CheckBoxTemplate();
	};
}

#endif
