/***********************************************************************
Vczh Library++ 3.0
Developer: Zihan Chen(vczh)
GacUI::CheckItemBackgroundTemplate

This file is generated by: Vczh GacUI Resource Code Generator
***********************************************************************/

#ifndef VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_CheckItemBackgroundTemplate
#define VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_CheckItemBackgroundTemplate

#include "HelloWorldPartialClasses.h"

namespace demos
{
	class CheckItemBackgroundTemplate : public CheckItemBackgroundTemplate_<CheckItemBackgroundTemplate>
	{
		friend class CheckItemBackgroundTemplate_<CheckItemBackgroundTemplate>;
		friend struct vl::reflection::description::CustomTypeDescriptorSelector<CheckItemBackgroundTemplate>;
	protected:

		// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)
		// #endregion CLASS_MEMBER_GUIEVENT_HANDLER
	public:
		CheckItemBackgroundTemplate();
	};
}

#endif
