/***********************************************************************
Vczh Library++ 3.0
Developer: Zihan Chen(vczh)
GacUI::CheckTextListTemplate

This file is generated by: Vczh GacUI Resource Code Generator
***********************************************************************/

#ifndef VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_CheckTextListTemplate
#define VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_CheckTextListTemplate

#include "HelloWorldPartialClasses.h"

namespace demos
{
	class CheckTextListTemplate : public CheckTextListTemplate_<CheckTextListTemplate>
	{
		friend class CheckTextListTemplate_<CheckTextListTemplate>;
		friend struct vl::reflection::description::CustomTypeDescriptorSelector<CheckTextListTemplate>;
	protected:

		// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)
		// #endregion CLASS_MEMBER_GUIEVENT_HANDLER
	public:
		CheckTextListTemplate();
	};
}

#endif
