/***********************************************************************
Vczh Library++ 3.0
Developer: Zihan Chen(vczh)
GacUI::ComboBoxTemplate

This file is generated by: Vczh GacUI Resource Code Generator
***********************************************************************/

#ifndef VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_ComboBoxTemplate
#define VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_ComboBoxTemplate

#include "HelloWorldPartialClasses.h"

namespace demos
{
	class ComboBoxTemplate : public ComboBoxTemplate_<ComboBoxTemplate>
	{
		friend class ComboBoxTemplate_<ComboBoxTemplate>;
		friend struct vl::reflection::description::CustomTypeDescriptorSelector<ComboBoxTemplate>;
	protected:

		// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)
		// #endregion CLASS_MEMBER_GUIEVENT_HANDLER
	public:
		ComboBoxTemplate();
	};
}

#endif
