/***********************************************************************
Vczh Library++ 3.0
Developer: Zihan Chen(vczh)
GacUI::DatePickerTemplate

This file is generated by: Vczh GacUI Resource Code Generator
***********************************************************************/

#ifndef VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_DatePickerTemplate
#define VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_DatePickerTemplate

#include "HelloWorldPartialClasses.h"

namespace demos
{
	class DatePickerTemplate : public DatePickerTemplate_<DatePickerTemplate>
	{
		friend class DatePickerTemplate_<DatePickerTemplate>;
		friend struct vl::reflection::description::CustomTypeDescriptorSelector<DatePickerTemplate>;
	protected:

		// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)
		// #endregion CLASS_MEMBER_GUIEVENT_HANDLER
	public:
		DatePickerTemplate();
	};
}

#endif
