/***********************************************************************
Vczh Library++ 3.0
Developer: Zihan Chen(vczh)
GacUI::DocumentLabelTemplate

This file is generated by: Vczh GacUI Resource Code Generator
***********************************************************************/

#ifndef VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_DocumentLabelTemplate
#define VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_DocumentLabelTemplate

#include "HelloWorldPartialClasses.h"

namespace demos
{
	class DocumentLabelTemplate : public DocumentLabelTemplate_<DocumentLabelTemplate>
	{
		friend class DocumentLabelTemplate_<DocumentLabelTemplate>;
		friend struct vl::reflection::description::CustomTypeDescriptorSelector<DocumentLabelTemplate>;
	protected:

		// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)
		// #endregion CLASS_MEMBER_GUIEVENT_HANDLER
	public:
		DocumentLabelTemplate();
	};
}

#endif
