/***********************************************************************
Vczh Library++ 3.0
Developer: Zihan Chen(vczh)
GacUI::ExpandingDecoratorTemplate

This file is generated by: Vczh GacUI Resource Code Generator
***********************************************************************/

#ifndef VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_ExpandingDecoratorTemplate
#define VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_ExpandingDecoratorTemplate

#include "HelloWorldPartialClasses.h"

namespace demos
{
	class ExpandingDecoratorTemplate : public ExpandingDecoratorTemplate_<ExpandingDecoratorTemplate>
	{
		friend class ExpandingDecoratorTemplate_<ExpandingDecoratorTemplate>;
		friend struct vl::reflection::description::CustomTypeDescriptorSelector<ExpandingDecoratorTemplate>;
	protected:

		// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)
		// #endregion CLASS_MEMBER_GUIEVENT_HANDLER
	public:
		ExpandingDecoratorTemplate();
	};
}

#endif
