/***********************************************************************
Vczh Library++ 3.0
Developer: Zihan Chen(vczh)
GacUI::GroupBoxTemplate

This file is generated by: Vczh GacUI Resource Code Generator
***********************************************************************/

#ifndef VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_GroupBoxTemplate
#define VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_GroupBoxTemplate

#include "HelloWorldPartialClasses.h"

namespace demos
{
	class GroupBoxTemplate : public GroupBoxTemplate_<GroupBoxTemplate>
	{
		friend class GroupBoxTemplate_<GroupBoxTemplate>;
		friend struct vl::reflection::description::CustomTypeDescriptorSelector<GroupBoxTemplate>;
	protected:

		// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)
		// #endregion CLASS_MEMBER_GUIEVENT_HANDLER
	public:
		GroupBoxTemplate();
	};
}

#endif
