/***********************************************************************
Vczh Library++ 3.0
Developer: Zihan Chen(vczh)
GacUI::Partial Classes

This file is generated by: Vczh GacUI Resource Code Generator
************************************************************************
DO NOT MODIFY
***********************************************************************/

#include "HelloWorld.h"

namespace darkskin
{
	// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)

	// #endregion CLASS_MEMBER_GUIEVENT_HANDLER

	BottomScrollButtonTemplate::BottomScrollButtonTemplate()
	{
		InitializeComponents();
	}
}


namespace darkskin
{
	// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)

	// #endregion CLASS_MEMBER_GUIEVENT_HANDLER

	ButtonTemplate::ButtonTemplate()
	{
		InitializeComponents();
	}
}


namespace darkskin
{
	// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)

	// #endregion CLASS_MEMBER_GUIEVENT_HANDLER

	CheckBoxTemplate::CheckBoxTemplate()
	{
		InitializeComponents();
	}
}


namespace darkskin
{
	// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)

	// #endregion CLASS_MEMBER_GUIEVENT_HANDLER

	CheckItemBackgroundTemplate::CheckItemBackgroundTemplate()
	{
		InitializeComponents();
	}
}


namespace darkskin
{
	// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)

	// #endregion CLASS_MEMBER_GUIEVENT_HANDLER

	CheckTextListTemplate::CheckTextListTemplate()
	{
		InitializeComponents();
	}
}


namespace darkskin
{
	// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)

	// #endregion CLASS_MEMBER_GUIEVENT_HANDLER

	ComboBoxTemplate::ComboBoxTemplate()
	{
		InitializeComponents();
	}
}


namespace darkskin
{
	// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)

	// #endregion CLASS_MEMBER_GUIEVENT_HANDLER

	DatePickerTemplate::DatePickerTemplate()
	{
		InitializeComponents();
	}
}


namespace darkskin
{
	// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)

	// #endregion CLASS_MEMBER_GUIEVENT_HANDLER

	DocumentLabelTemplate::DocumentLabelTemplate()
	{
		InitializeComponents();
	}
}


namespace darkskin
{
	// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)

	// #endregion CLASS_MEMBER_GUIEVENT_HANDLER

	DocumentViewerTemplate::DocumentViewerTemplate()
	{
		InitializeComponents();
	}
}


namespace darkskin
{
	// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)

	// #endregion CLASS_MEMBER_GUIEVENT_HANDLER

	ExpandingDecoratorTemplate::ExpandingDecoratorTemplate()
	{
		InitializeComponents();
	}
}


namespace darkskin
{
	// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)

	// #endregion CLASS_MEMBER_GUIEVENT_HANDLER

	GroupBoxTemplate::GroupBoxTemplate()
	{
		InitializeComponents();
	}
}


namespace darkskin
{
	// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)

	// #endregion CLASS_MEMBER_GUIEVENT_HANDLER

	HScrollHandleTemplate::HScrollHandleTemplate()
	{
		InitializeComponents();
	}
}


namespace darkskin
{
	// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)

	// #endregion CLASS_MEMBER_GUIEVENT_HANDLER

	ItemBackgroundTemplate::ItemBackgroundTemplate()
	{
		InitializeComponents();
	}
}


namespace darkskin
{
	// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)

	// #endregion CLASS_MEMBER_GUIEVENT_HANDLER

	LabelTemplate::LabelTemplate()
	{
		InitializeComponents();
	}
}


namespace darkskin
{
	// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)

	// #endregion CLASS_MEMBER_GUIEVENT_HANDLER

	LeftScrollButtonTemplate::LeftScrollButtonTemplate()
	{
		InitializeComponents();
	}
}


namespace darkskin
{
	// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)

	// #endregion CLASS_MEMBER_GUIEVENT_HANDLER

	ListViewColumnHeaderTemplate::ListViewColumnHeaderTemplate()
	{
		InitializeComponents();
	}
}


namespace darkskin
{
	// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)

	// #endregion CLASS_MEMBER_GUIEVENT_HANDLER

	ListViewTemplate::ListViewTemplate()
	{
		InitializeComponents();
	}
}


namespace darkskin
{
	// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)

	// #endregion CLASS_MEMBER_GUIEVENT_HANDLER

	MenuBarButtonTemplate::MenuBarButtonTemplate()
	{
		InitializeComponents();
	}
}


namespace darkskin
{
	// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)

	// #endregion CLASS_MEMBER_GUIEVENT_HANDLER

	MenuItemButtonTemplate::MenuItemButtonTemplate()
	{
		InitializeComponents();
	}
}


namespace darkskin
{
	// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)

	// #endregion CLASS_MEMBER_GUIEVENT_HANDLER

	MenuSplitterTemplate::MenuSplitterTemplate()
	{
		InitializeComponents();
	}
}


namespace darkskin
{
	// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)

	// #endregion CLASS_MEMBER_GUIEVENT_HANDLER

	MultilineTextBoxTemplate::MultilineTextBoxTemplate()
	{
		InitializeComponents();
	}
}


namespace darkskin
{
	// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)

	// #endregion CLASS_MEMBER_GUIEVENT_HANDLER

	ProgressBarTemplate::ProgressBarTemplate()
	{
		InitializeComponents();
	}
}


namespace darkskin
{
	// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)

	// #endregion CLASS_MEMBER_GUIEVENT_HANDLER

	RadioButtonTemplate::RadioButtonTemplate()
	{
		InitializeComponents();
	}
}


namespace darkskin
{
	// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)

	// #endregion CLASS_MEMBER_GUIEVENT_HANDLER

	RadioTextListTemplate::RadioTextListTemplate()
	{
		InitializeComponents();
	}
}


namespace darkskin
{
	// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)

	// #endregion CLASS_MEMBER_GUIEVENT_HANDLER

	RightScrollButtonTemplate::RightScrollButtonTemplate()
	{
		InitializeComponents();
	}
}


namespace darkskin
{
	// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)

	// #endregion CLASS_MEMBER_GUIEVENT_HANDLER

	ScrollViewTemplate::ScrollViewTemplate()
	{
		InitializeComponents();
	}
}


namespace darkskin
{
	// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)

	// #endregion CLASS_MEMBER_GUIEVENT_HANDLER

	SinglelineTextBoxTemplate::SinglelineTextBoxTemplate()
	{
		InitializeComponents();
	}
}


namespace darkskin
{
	// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)

	// #endregion CLASS_MEMBER_GUIEVENT_HANDLER

	TabDropdownTemplate::TabDropdownTemplate()
	{
		InitializeComponents();
	}
}


namespace darkskin
{
	// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)

	// #endregion CLASS_MEMBER_GUIEVENT_HANDLER

	TabHeaderTemplate::TabHeaderTemplate()
	{
		InitializeComponents();
	}
}


namespace darkskin
{
	// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)

	// #endregion CLASS_MEMBER_GUIEVENT_HANDLER

	TabTemplate::TabTemplate()
	{
		InitializeComponents();
	}
}


namespace darkskin
{
	// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)

	// #endregion CLASS_MEMBER_GUIEVENT_HANDLER

	TextListTemplate::TextListTemplate()
	{
		InitializeComponents();
	}
}


namespace darkskin
{
	// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)

	// #endregion CLASS_MEMBER_GUIEVENT_HANDLER

	ToolstripButtonTemplate::ToolstripButtonTemplate()
	{
		InitializeComponents();
	}
}


namespace darkskin
{
	// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)

	// #endregion CLASS_MEMBER_GUIEVENT_HANDLER

	ToolstripDropdownButtonTemplate::ToolstripDropdownButtonTemplate()
	{
		InitializeComponents();
	}
}


namespace darkskin
{
	// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)

	// #endregion CLASS_MEMBER_GUIEVENT_HANDLER

	ToolstripMenuTemplate::ToolstripMenuTemplate()
	{
		InitializeComponents();
	}
}


namespace darkskin
{
	// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)

	// #endregion CLASS_MEMBER_GUIEVENT_HANDLER

	ToolstripSplitArrowTemplate::ToolstripSplitArrowTemplate()
	{
		InitializeComponents();
	}
}


namespace darkskin
{
	// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)

	// #endregion CLASS_MEMBER_GUIEVENT_HANDLER

	ToolstripSplitButtonTemplate::ToolstripSplitButtonTemplate()
	{
		InitializeComponents();
	}
}


namespace darkskin
{
	// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)

	// #endregion CLASS_MEMBER_GUIEVENT_HANDLER

	ToolstripSplitterTemplate::ToolstripSplitterTemplate()
	{
		InitializeComponents();
	}
}


namespace darkskin
{
	// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)

	// #endregion CLASS_MEMBER_GUIEVENT_HANDLER

	ToolstripTemplate::ToolstripTemplate()
	{
		InitializeComponents();
	}
}


namespace darkskin
{
	// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)

	// #endregion CLASS_MEMBER_GUIEVENT_HANDLER

	TooltipTemplate::TooltipTemplate()
	{
		InitializeComponents();
	}
}


namespace darkskin
{
	// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)

	// #endregion CLASS_MEMBER_GUIEVENT_HANDLER

	TopScrollButtonTemplate::TopScrollButtonTemplate()
	{
		InitializeComponents();
	}
}


namespace darkskin
{
	// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)

	// #endregion CLASS_MEMBER_GUIEVENT_HANDLER

	TreeViewTemplate::TreeViewTemplate()
	{
		InitializeComponents();
	}
}


namespace darkskin
{
	// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)

	// #endregion CLASS_MEMBER_GUIEVENT_HANDLER

	VScrollHandleTemplate::VScrollHandleTemplate()
	{
		InitializeComponents();
	}
}


namespace darkskin
{
	// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)

	// #endregion CLASS_MEMBER_GUIEVENT_HANDLER

	WindowTemplate::WindowTemplate()
	{
		InitializeComponents();
	}
}


namespace vl
{
	namespace reflection
	{
		namespace description
		{
			#define _ ,
			IMPL_CPP_TYPE_INFO(darkskin::BottomScrollButtonTemplate)
			IMPL_CPP_TYPE_INFO(darkskin::ButtonTemplate)
			IMPL_CPP_TYPE_INFO(darkskin::CheckBoxTemplate)
			IMPL_CPP_TYPE_INFO(darkskin::CheckItemBackgroundTemplate)
			IMPL_CPP_TYPE_INFO(darkskin::CheckTextListTemplate)
			IMPL_CPP_TYPE_INFO(darkskin::ComboBoxTemplate)
			IMPL_CPP_TYPE_INFO(darkskin::DatePickerTemplate)
			IMPL_CPP_TYPE_INFO(darkskin::DocumentLabelTemplate)
			IMPL_CPP_TYPE_INFO(darkskin::DocumentViewerTemplate)
			IMPL_CPP_TYPE_INFO(darkskin::ExpandingDecoratorTemplate)
			IMPL_CPP_TYPE_INFO(darkskin::GroupBoxTemplate)
			IMPL_CPP_TYPE_INFO(darkskin::HScrollHandleTemplate)
			IMPL_CPP_TYPE_INFO(darkskin::HScrollTemplate)
			IMPL_CPP_TYPE_INFO(darkskin::HTrackerTemplate)
			IMPL_CPP_TYPE_INFO(darkskin::ItemBackgroundTemplate)
			IMPL_CPP_TYPE_INFO(darkskin::LabelTemplate)
			IMPL_CPP_TYPE_INFO(darkskin::LeftScrollButtonTemplate)
			IMPL_CPP_TYPE_INFO(darkskin::ListViewColumnHeaderTemplate)
			IMPL_CPP_TYPE_INFO(darkskin::ListViewTemplate)
			IMPL_CPP_TYPE_INFO(darkskin::MenuBarButtonTemplate)
			IMPL_CPP_TYPE_INFO(darkskin::MenuItemButtonTemplate)
			IMPL_CPP_TYPE_INFO(darkskin::MenuSplitterTemplate)
			IMPL_CPP_TYPE_INFO(darkskin::MultilineTextBoxTemplate)
			IMPL_CPP_TYPE_INFO(darkskin::ProgressBarTemplate)
			IMPL_CPP_TYPE_INFO(darkskin::RadioButtonTemplate)
			IMPL_CPP_TYPE_INFO(darkskin::RadioTextListTemplate)
			IMPL_CPP_TYPE_INFO(darkskin::RightScrollButtonTemplate)
			IMPL_CPP_TYPE_INFO(darkskin::ScrollViewTemplate)
			IMPL_CPP_TYPE_INFO(darkskin::SinglelineTextBoxTemplate)
			IMPL_CPP_TYPE_INFO(darkskin::TabDropdownTemplate)
			IMPL_CPP_TYPE_INFO(darkskin::TabHeaderTemplate)
			IMPL_CPP_TYPE_INFO(darkskin::TabTemplate)
			IMPL_CPP_TYPE_INFO(darkskin::TextListTemplate)
			IMPL_CPP_TYPE_INFO(darkskin::ToolstripButtonTemplate)
			IMPL_CPP_TYPE_INFO(darkskin::ToolstripDropdownButtonTemplate)
			IMPL_CPP_TYPE_INFO(darkskin::ToolstripMenuTemplate)
			IMPL_CPP_TYPE_INFO(darkskin::ToolstripSplitArrowTemplate)
			IMPL_CPP_TYPE_INFO(darkskin::ToolstripSplitButtonTemplate)
			IMPL_CPP_TYPE_INFO(darkskin::ToolstripSplitterTemplate)
			IMPL_CPP_TYPE_INFO(darkskin::ToolstripTemplate)
			IMPL_CPP_TYPE_INFO(darkskin::TooltipTemplate)
			IMPL_CPP_TYPE_INFO(darkskin::TopScrollButtonTemplate)
			IMPL_CPP_TYPE_INFO(darkskin::TreeViewTemplate)
			IMPL_CPP_TYPE_INFO(darkskin::VScrollHandleTemplate)
			IMPL_CPP_TYPE_INFO(darkskin::VScrollTemplate)
			IMPL_CPP_TYPE_INFO(darkskin::VTrackerTemplate)
			IMPL_CPP_TYPE_INFO(darkskin::WindowTemplate)
			IMPL_CPP_TYPE_INFO(demos::MainWindow)

			BEGIN_CLASS_MEMBER(darkskin::BottomScrollButtonTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiButtonTemplate)
				CLASS_MEMBER_CONSTRUCTOR(darkskin::BottomScrollButtonTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(darkskin::BottomScrollButtonTemplate)

			BEGIN_CLASS_MEMBER(darkskin::ButtonTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiButtonTemplate)
				CLASS_MEMBER_CONSTRUCTOR(darkskin::ButtonTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(darkskin::ButtonTemplate)

			BEGIN_CLASS_MEMBER(darkskin::CheckBoxTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiSelectableButtonTemplate)
				CLASS_MEMBER_CONSTRUCTOR(darkskin::CheckBoxTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(darkskin::CheckBoxTemplate)

			BEGIN_CLASS_MEMBER(darkskin::CheckItemBackgroundTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiSelectableButtonTemplate)
				CLASS_MEMBER_CONSTRUCTOR(darkskin::CheckItemBackgroundTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(darkskin::CheckItemBackgroundTemplate)

			BEGIN_CLASS_MEMBER(darkskin::CheckTextListTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiTextListTemplate)
				CLASS_MEMBER_CONSTRUCTOR(darkskin::CheckTextListTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(darkskin::CheckTextListTemplate)

			BEGIN_CLASS_MEMBER(darkskin::ComboBoxTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiDateComboBoxTemplate)
				CLASS_MEMBER_CONSTRUCTOR(darkskin::ComboBoxTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(darkskin::ComboBoxTemplate)

			BEGIN_CLASS_MEMBER(darkskin::DatePickerTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiDatePickerTemplate)
				CLASS_MEMBER_CONSTRUCTOR(darkskin::DatePickerTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(darkskin::DatePickerTemplate)

			BEGIN_CLASS_MEMBER(darkskin::DocumentLabelTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiDocumentLabelTemplate)
				CLASS_MEMBER_CONSTRUCTOR(darkskin::DocumentLabelTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(darkskin::DocumentLabelTemplate)

			BEGIN_CLASS_MEMBER(darkskin::DocumentViewerTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiDocumentViewerTemplate)
				CLASS_MEMBER_CONSTRUCTOR(darkskin::DocumentViewerTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(darkskin::DocumentViewerTemplate)

			BEGIN_CLASS_MEMBER(darkskin::ExpandingDecoratorTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiSelectableButtonTemplate)
				CLASS_MEMBER_CONSTRUCTOR(darkskin::ExpandingDecoratorTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(darkskin::ExpandingDecoratorTemplate)

			BEGIN_CLASS_MEMBER(darkskin::GroupBoxTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiControlTemplate)
				CLASS_MEMBER_CONSTRUCTOR(darkskin::GroupBoxTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(darkskin::GroupBoxTemplate)

			BEGIN_CLASS_MEMBER(darkskin::HScrollHandleTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiButtonTemplate)
				CLASS_MEMBER_CONSTRUCTOR(darkskin::HScrollHandleTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(darkskin::HScrollHandleTemplate)

			BEGIN_CLASS_MEMBER(darkskin::HScrollTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiScrollTemplate)
				CLASS_MEMBER_CONSTRUCTOR(darkskin::HScrollTemplate*(), NO_PARAMETER)

				CLASS_MEMBER_GUIEVENT_HANDLER(OnHandleMouseDown, vl::presentation::compositions::GuiMouseEventArgs)
				CLASS_MEMBER_GUIEVENT_HANDLER(OnHandleMouseMove, vl::presentation::compositions::GuiMouseEventArgs)
				CLASS_MEMBER_GUIEVENT_HANDLER(OnHandleMouseUp, vl::presentation::compositions::GuiMouseEventArgs)
			END_CLASS_MEMBER(darkskin::HScrollTemplate)

			BEGIN_CLASS_MEMBER(darkskin::HTrackerTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiScrollTemplate)
				CLASS_MEMBER_CONSTRUCTOR(darkskin::HTrackerTemplate*(), NO_PARAMETER)

				CLASS_MEMBER_GUIEVENT_HANDLER(OnHandleMouseDown, vl::presentation::compositions::GuiMouseEventArgs)
				CLASS_MEMBER_GUIEVENT_HANDLER(OnHandleMouseMove, vl::presentation::compositions::GuiMouseEventArgs)
				CLASS_MEMBER_GUIEVENT_HANDLER(OnHandleMouseUp, vl::presentation::compositions::GuiMouseEventArgs)
			END_CLASS_MEMBER(darkskin::HTrackerTemplate)

			BEGIN_CLASS_MEMBER(darkskin::ItemBackgroundTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiSelectableButtonTemplate)
				CLASS_MEMBER_CONSTRUCTOR(darkskin::ItemBackgroundTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(darkskin::ItemBackgroundTemplate)

			BEGIN_CLASS_MEMBER(darkskin::LabelTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiLabelTemplate)
				CLASS_MEMBER_CONSTRUCTOR(darkskin::LabelTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(darkskin::LabelTemplate)

			BEGIN_CLASS_MEMBER(darkskin::LeftScrollButtonTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiButtonTemplate)
				CLASS_MEMBER_CONSTRUCTOR(darkskin::LeftScrollButtonTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(darkskin::LeftScrollButtonTemplate)

			BEGIN_CLASS_MEMBER(darkskin::ListViewColumnHeaderTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiListViewColumnHeaderTemplate)
				CLASS_MEMBER_CONSTRUCTOR(darkskin::ListViewColumnHeaderTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(darkskin::ListViewColumnHeaderTemplate)

			BEGIN_CLASS_MEMBER(darkskin::ListViewTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiListViewTemplate)
				CLASS_MEMBER_CONSTRUCTOR(darkskin::ListViewTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(darkskin::ListViewTemplate)

			BEGIN_CLASS_MEMBER(darkskin::MenuBarButtonTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiToolstripButtonTemplate)
				CLASS_MEMBER_CONSTRUCTOR(darkskin::MenuBarButtonTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(darkskin::MenuBarButtonTemplate)

			BEGIN_CLASS_MEMBER(darkskin::MenuItemButtonTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiToolstripButtonTemplate)
				CLASS_MEMBER_CONSTRUCTOR(darkskin::MenuItemButtonTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(darkskin::MenuItemButtonTemplate)

			BEGIN_CLASS_MEMBER(darkskin::MenuSplitterTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiControlTemplate)
				CLASS_MEMBER_CONSTRUCTOR(darkskin::MenuSplitterTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(darkskin::MenuSplitterTemplate)

			BEGIN_CLASS_MEMBER(darkskin::MultilineTextBoxTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiMultilineTextBoxTemplate)
				CLASS_MEMBER_CONSTRUCTOR(darkskin::MultilineTextBoxTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(darkskin::MultilineTextBoxTemplate)

			BEGIN_CLASS_MEMBER(darkskin::ProgressBarTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiScrollTemplate)
				CLASS_MEMBER_CONSTRUCTOR(darkskin::ProgressBarTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(darkskin::ProgressBarTemplate)

			BEGIN_CLASS_MEMBER(darkskin::RadioButtonTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiSelectableButtonTemplate)
				CLASS_MEMBER_CONSTRUCTOR(darkskin::RadioButtonTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(darkskin::RadioButtonTemplate)

			BEGIN_CLASS_MEMBER(darkskin::RadioTextListTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiTextListTemplate)
				CLASS_MEMBER_CONSTRUCTOR(darkskin::RadioTextListTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(darkskin::RadioTextListTemplate)

			BEGIN_CLASS_MEMBER(darkskin::RightScrollButtonTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiButtonTemplate)
				CLASS_MEMBER_CONSTRUCTOR(darkskin::RightScrollButtonTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(darkskin::RightScrollButtonTemplate)

			BEGIN_CLASS_MEMBER(darkskin::ScrollViewTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiScrollViewTemplate)
				CLASS_MEMBER_CONSTRUCTOR(darkskin::ScrollViewTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(darkskin::ScrollViewTemplate)

			BEGIN_CLASS_MEMBER(darkskin::SinglelineTextBoxTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiSinglelineTextBoxTemplate)
				CLASS_MEMBER_CONSTRUCTOR(darkskin::SinglelineTextBoxTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(darkskin::SinglelineTextBoxTemplate)

			BEGIN_CLASS_MEMBER(darkskin::TabDropdownTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiButtonTemplate)
				CLASS_MEMBER_CONSTRUCTOR(darkskin::TabDropdownTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(darkskin::TabDropdownTemplate)

			BEGIN_CLASS_MEMBER(darkskin::TabHeaderTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiSelectableButtonTemplate)
				CLASS_MEMBER_CONSTRUCTOR(darkskin::TabHeaderTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(darkskin::TabHeaderTemplate)

			BEGIN_CLASS_MEMBER(darkskin::TabTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiTabTemplate)
				CLASS_MEMBER_CONSTRUCTOR(darkskin::TabTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(darkskin::TabTemplate)

			BEGIN_CLASS_MEMBER(darkskin::TextListTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiTextListTemplate)
				CLASS_MEMBER_CONSTRUCTOR(darkskin::TextListTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(darkskin::TextListTemplate)

			BEGIN_CLASS_MEMBER(darkskin::ToolstripButtonTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiToolstripButtonTemplate)
				CLASS_MEMBER_CONSTRUCTOR(darkskin::ToolstripButtonTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(darkskin::ToolstripButtonTemplate)

			BEGIN_CLASS_MEMBER(darkskin::ToolstripDropdownButtonTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiToolstripButtonTemplate)
				CLASS_MEMBER_CONSTRUCTOR(darkskin::ToolstripDropdownButtonTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(darkskin::ToolstripDropdownButtonTemplate)

			BEGIN_CLASS_MEMBER(darkskin::ToolstripMenuTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiMenuTemplate)
				CLASS_MEMBER_CONSTRUCTOR(darkskin::ToolstripMenuTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(darkskin::ToolstripMenuTemplate)

			BEGIN_CLASS_MEMBER(darkskin::ToolstripSplitArrowTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiSelectableButtonTemplate)
				CLASS_MEMBER_CONSTRUCTOR(darkskin::ToolstripSplitArrowTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(darkskin::ToolstripSplitArrowTemplate)

			BEGIN_CLASS_MEMBER(darkskin::ToolstripSplitButtonTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiToolstripButtonTemplate)
				CLASS_MEMBER_CONSTRUCTOR(darkskin::ToolstripSplitButtonTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(darkskin::ToolstripSplitButtonTemplate)

			BEGIN_CLASS_MEMBER(darkskin::ToolstripSplitterTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiControlTemplate)
				CLASS_MEMBER_CONSTRUCTOR(darkskin::ToolstripSplitterTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(darkskin::ToolstripSplitterTemplate)

			BEGIN_CLASS_MEMBER(darkskin::ToolstripTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiControlTemplate)
				CLASS_MEMBER_CONSTRUCTOR(darkskin::ToolstripTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(darkskin::ToolstripTemplate)

			BEGIN_CLASS_MEMBER(darkskin::TooltipTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiWindowTemplate)
				CLASS_MEMBER_CONSTRUCTOR(darkskin::TooltipTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(darkskin::TooltipTemplate)

			BEGIN_CLASS_MEMBER(darkskin::TopScrollButtonTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiButtonTemplate)
				CLASS_MEMBER_CONSTRUCTOR(darkskin::TopScrollButtonTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(darkskin::TopScrollButtonTemplate)

			BEGIN_CLASS_MEMBER(darkskin::TreeViewTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiTreeViewTemplate)
				CLASS_MEMBER_CONSTRUCTOR(darkskin::TreeViewTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(darkskin::TreeViewTemplate)

			BEGIN_CLASS_MEMBER(darkskin::VScrollHandleTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiButtonTemplate)
				CLASS_MEMBER_CONSTRUCTOR(darkskin::VScrollHandleTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(darkskin::VScrollHandleTemplate)

			BEGIN_CLASS_MEMBER(darkskin::VScrollTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiScrollTemplate)
				CLASS_MEMBER_CONSTRUCTOR(darkskin::VScrollTemplate*(), NO_PARAMETER)

				CLASS_MEMBER_GUIEVENT_HANDLER(OnHandleMouseDown, vl::presentation::compositions::GuiMouseEventArgs)
				CLASS_MEMBER_GUIEVENT_HANDLER(OnHandleMouseMove, vl::presentation::compositions::GuiMouseEventArgs)
				CLASS_MEMBER_GUIEVENT_HANDLER(OnHandleMouseUp, vl::presentation::compositions::GuiMouseEventArgs)
			END_CLASS_MEMBER(darkskin::VScrollTemplate)

			BEGIN_CLASS_MEMBER(darkskin::VTrackerTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiScrollTemplate)
				CLASS_MEMBER_CONSTRUCTOR(darkskin::VTrackerTemplate*(), NO_PARAMETER)

				CLASS_MEMBER_GUIEVENT_HANDLER(OnHandleMouseDown, vl::presentation::compositions::GuiMouseEventArgs)
				CLASS_MEMBER_GUIEVENT_HANDLER(OnHandleMouseMove, vl::presentation::compositions::GuiMouseEventArgs)
				CLASS_MEMBER_GUIEVENT_HANDLER(OnHandleMouseUp, vl::presentation::compositions::GuiMouseEventArgs)
			END_CLASS_MEMBER(darkskin::VTrackerTemplate)

			BEGIN_CLASS_MEMBER(darkskin::WindowTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiWindowTemplate)
				CLASS_MEMBER_CONSTRUCTOR(darkskin::WindowTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(darkskin::WindowTemplate)

			BEGIN_CLASS_MEMBER(demos::MainWindow)
				CLASS_MEMBER_BASE(vl::presentation::controls::GuiWindow)
				CLASS_MEMBER_CONSTRUCTOR(demos::MainWindow*(), NO_PARAMETER)
			END_CLASS_MEMBER(demos::MainWindow)

			#undef _

			class HelloWorldResourceLoader : public Object, public ITypeLoader
			{
			public:
				void Load(ITypeManager* manager)
				{
					ADD_TYPE_INFO(darkskin::BottomScrollButtonTemplate)
					ADD_TYPE_INFO(darkskin::ButtonTemplate)
					ADD_TYPE_INFO(darkskin::CheckBoxTemplate)
					ADD_TYPE_INFO(darkskin::CheckItemBackgroundTemplate)
					ADD_TYPE_INFO(darkskin::CheckTextListTemplate)
					ADD_TYPE_INFO(darkskin::ComboBoxTemplate)
					ADD_TYPE_INFO(darkskin::DatePickerTemplate)
					ADD_TYPE_INFO(darkskin::DocumentLabelTemplate)
					ADD_TYPE_INFO(darkskin::DocumentViewerTemplate)
					ADD_TYPE_INFO(darkskin::ExpandingDecoratorTemplate)
					ADD_TYPE_INFO(darkskin::GroupBoxTemplate)
					ADD_TYPE_INFO(darkskin::HScrollHandleTemplate)
					ADD_TYPE_INFO(darkskin::HScrollTemplate)
					ADD_TYPE_INFO(darkskin::HTrackerTemplate)
					ADD_TYPE_INFO(darkskin::ItemBackgroundTemplate)
					ADD_TYPE_INFO(darkskin::LabelTemplate)
					ADD_TYPE_INFO(darkskin::LeftScrollButtonTemplate)
					ADD_TYPE_INFO(darkskin::ListViewColumnHeaderTemplate)
					ADD_TYPE_INFO(darkskin::ListViewTemplate)
					ADD_TYPE_INFO(darkskin::MenuBarButtonTemplate)
					ADD_TYPE_INFO(darkskin::MenuItemButtonTemplate)
					ADD_TYPE_INFO(darkskin::MenuSplitterTemplate)
					ADD_TYPE_INFO(darkskin::MultilineTextBoxTemplate)
					ADD_TYPE_INFO(darkskin::ProgressBarTemplate)
					ADD_TYPE_INFO(darkskin::RadioButtonTemplate)
					ADD_TYPE_INFO(darkskin::RadioTextListTemplate)
					ADD_TYPE_INFO(darkskin::RightScrollButtonTemplate)
					ADD_TYPE_INFO(darkskin::ScrollViewTemplate)
					ADD_TYPE_INFO(darkskin::SinglelineTextBoxTemplate)
					ADD_TYPE_INFO(darkskin::TabDropdownTemplate)
					ADD_TYPE_INFO(darkskin::TabHeaderTemplate)
					ADD_TYPE_INFO(darkskin::TabTemplate)
					ADD_TYPE_INFO(darkskin::TextListTemplate)
					ADD_TYPE_INFO(darkskin::ToolstripButtonTemplate)
					ADD_TYPE_INFO(darkskin::ToolstripDropdownButtonTemplate)
					ADD_TYPE_INFO(darkskin::ToolstripMenuTemplate)
					ADD_TYPE_INFO(darkskin::ToolstripSplitArrowTemplate)
					ADD_TYPE_INFO(darkskin::ToolstripSplitButtonTemplate)
					ADD_TYPE_INFO(darkskin::ToolstripSplitterTemplate)
					ADD_TYPE_INFO(darkskin::ToolstripTemplate)
					ADD_TYPE_INFO(darkskin::TooltipTemplate)
					ADD_TYPE_INFO(darkskin::TopScrollButtonTemplate)
					ADD_TYPE_INFO(darkskin::TreeViewTemplate)
					ADD_TYPE_INFO(darkskin::VScrollHandleTemplate)
					ADD_TYPE_INFO(darkskin::VScrollTemplate)
					ADD_TYPE_INFO(darkskin::VTrackerTemplate)
					ADD_TYPE_INFO(darkskin::WindowTemplate)
					ADD_TYPE_INFO(demos::MainWindow)
				}

				void Unload(ITypeManager* manager)
				{
				}
			};

			class HelloWorldResourcePlugin : public Object, public vl::presentation::controls::IGuiPlugin
			{
			public:
				void Load()override
				{
					GetGlobalTypeManager()->AddTypeLoader(new HelloWorldResourceLoader);
				}

				void AfterLoad()override
				{
				}

				void Unload()override
				{
				}
			};
			GUI_REGISTER_PLUGIN(HelloWorldResourcePlugin)
		}
	}
}

