/***********************************************************************
Vczh Library++ 3.0
Developer: Zihan Chen(vczh)
GacUI::Partial Classes

This file is generated by: Vczh GacUI Resource Code Generator
************************************************************************
DO NOT MODIFY
***********************************************************************/

#include "HelloWorld.h"

namespace vl
{
	namespace reflection
	{
		namespace description
		{
			#define _ ,
			IMPL_CPP_TYPE_INFO(demos::BottomScrollButtonTemplate)
			IMPL_CPP_TYPE_INFO(demos::ButtonTemplate)
			IMPL_CPP_TYPE_INFO(demos::CheckBoxTemplate)
			IMPL_CPP_TYPE_INFO(demos::CheckItemBackgroundTemplate)
			IMPL_CPP_TYPE_INFO(demos::CheckTextListTemplate)
			IMPL_CPP_TYPE_INFO(demos::ComboBoxTemplate)
			IMPL_CPP_TYPE_INFO(demos::DatePickerTemplate)
			IMPL_CPP_TYPE_INFO(demos::DocumentLabelTemplate)
			IMPL_CPP_TYPE_INFO(demos::ExpandingDecoratorTemplate)
			IMPL_CPP_TYPE_INFO(demos::GroupBoxTemplate)
			IMPL_CPP_TYPE_INFO(demos::HScrollHandleTemplate)
			IMPL_CPP_TYPE_INFO(demos::HScrollTemplate)
			IMPL_CPP_TYPE_INFO(demos::HTrackerTemplate)
			IMPL_CPP_TYPE_INFO(demos::ItemBackgroundTemplate)
			IMPL_CPP_TYPE_INFO(demos::LabelTemplate)
			IMPL_CPP_TYPE_INFO(demos::LeftScrollButtonTemplate)
			IMPL_CPP_TYPE_INFO(demos::ListViewColumnHeaderTemplate)
			IMPL_CPP_TYPE_INFO(demos::ListViewTemplate)
			IMPL_CPP_TYPE_INFO(demos::MainWindow)
			IMPL_CPP_TYPE_INFO(demos::MenuBarButtonTemplate)
			IMPL_CPP_TYPE_INFO(demos::MenuItemButtonTemplate)
			IMPL_CPP_TYPE_INFO(demos::MenuSplitterTemplate)
			IMPL_CPP_TYPE_INFO(demos::MultilineTextBoxTemplate)
			IMPL_CPP_TYPE_INFO(demos::ProgressBarTemplate)
			IMPL_CPP_TYPE_INFO(demos::RadioButtonTemplate)
			IMPL_CPP_TYPE_INFO(demos::RadioTextListTemplate)
			IMPL_CPP_TYPE_INFO(demos::RightScrollButtonTemplate)
			IMPL_CPP_TYPE_INFO(demos::ScrollViewTemplate)
			IMPL_CPP_TYPE_INFO(demos::SinglelineTextBoxTemplate)
			IMPL_CPP_TYPE_INFO(demos::TabDropdownTemplate)
			IMPL_CPP_TYPE_INFO(demos::TabHeaderTemplate)
			IMPL_CPP_TYPE_INFO(demos::TabTemplate)
			IMPL_CPP_TYPE_INFO(demos::TextListTemplate)
			IMPL_CPP_TYPE_INFO(demos::ToolstripButtonTemplate)
			IMPL_CPP_TYPE_INFO(demos::ToolstripDropdownButtonTemplate)
			IMPL_CPP_TYPE_INFO(demos::ToolstripMenuTemplate)
			IMPL_CPP_TYPE_INFO(demos::ToolstripSplitArrowTemplate)
			IMPL_CPP_TYPE_INFO(demos::ToolstripSplitButtonTemplate)
			IMPL_CPP_TYPE_INFO(demos::ToolstripSplitterTemplate)
			IMPL_CPP_TYPE_INFO(demos::ToolstripTemplate)
			IMPL_CPP_TYPE_INFO(demos::TooltipTemplate)
			IMPL_CPP_TYPE_INFO(demos::TopScrollButtonTemplate)
			IMPL_CPP_TYPE_INFO(demos::TreeViewTemplate)
			IMPL_CPP_TYPE_INFO(demos::VScrollHandleTemplate)
			IMPL_CPP_TYPE_INFO(demos::VScrollTemplate)
			IMPL_CPP_TYPE_INFO(demos::VTrackerTemplate)
			IMPL_CPP_TYPE_INFO(demos::WindowTemplate)

			BEGIN_CLASS_MEMBER(demos::BottomScrollButtonTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiButtonTemplate)
				CLASS_MEMBER_CONSTRUCTOR(demos::BottomScrollButtonTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(demos::BottomScrollButtonTemplate)

			BEGIN_CLASS_MEMBER(demos::ButtonTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiButtonTemplate)
				CLASS_MEMBER_CONSTRUCTOR(demos::ButtonTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(demos::ButtonTemplate)

			BEGIN_CLASS_MEMBER(demos::CheckBoxTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiSelectableButtonTemplate)
				CLASS_MEMBER_CONSTRUCTOR(demos::CheckBoxTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(demos::CheckBoxTemplate)

			BEGIN_CLASS_MEMBER(demos::CheckItemBackgroundTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiSelectableButtonTemplate)
				CLASS_MEMBER_CONSTRUCTOR(demos::CheckItemBackgroundTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(demos::CheckItemBackgroundTemplate)

			BEGIN_CLASS_MEMBER(demos::CheckTextListTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiTextListTemplate)
				CLASS_MEMBER_CONSTRUCTOR(demos::CheckTextListTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(demos::CheckTextListTemplate)

			BEGIN_CLASS_MEMBER(demos::ComboBoxTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiDateComboBoxTemplate)
				CLASS_MEMBER_CONSTRUCTOR(demos::ComboBoxTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(demos::ComboBoxTemplate)

			BEGIN_CLASS_MEMBER(demos::DatePickerTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiDatePickerTemplate)
				CLASS_MEMBER_CONSTRUCTOR(demos::DatePickerTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(demos::DatePickerTemplate)

			BEGIN_CLASS_MEMBER(demos::DocumentLabelTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiControlTemplate)
				CLASS_MEMBER_CONSTRUCTOR(demos::DocumentLabelTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(demos::DocumentLabelTemplate)

			BEGIN_CLASS_MEMBER(demos::ExpandingDecoratorTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiSelectableButtonTemplate)
				CLASS_MEMBER_CONSTRUCTOR(demos::ExpandingDecoratorTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(demos::ExpandingDecoratorTemplate)

			BEGIN_CLASS_MEMBER(demos::GroupBoxTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiControlTemplate)
				CLASS_MEMBER_CONSTRUCTOR(demos::GroupBoxTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(demos::GroupBoxTemplate)

			BEGIN_CLASS_MEMBER(demos::HScrollHandleTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiButtonTemplate)
				CLASS_MEMBER_CONSTRUCTOR(demos::HScrollHandleTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(demos::HScrollHandleTemplate)

			BEGIN_CLASS_MEMBER(demos::HScrollTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiScrollTemplate)
				CLASS_MEMBER_CONSTRUCTOR(demos::HScrollTemplate*(), NO_PARAMETER)

				CLASS_MEMBER_GUIEVENT_HANDLER(OnHandleMouseDown, vl::presentation::compositions::GuiMouseEventArgs)
				CLASS_MEMBER_GUIEVENT_HANDLER(OnHandleMouseMove, vl::presentation::compositions::GuiMouseEventArgs)
				CLASS_MEMBER_GUIEVENT_HANDLER(OnHandleMouseUp, vl::presentation::compositions::GuiMouseEventArgs)
			END_CLASS_MEMBER(demos::HScrollTemplate)

			BEGIN_CLASS_MEMBER(demos::HTrackerTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiScrollTemplate)
				CLASS_MEMBER_CONSTRUCTOR(demos::HTrackerTemplate*(), NO_PARAMETER)

				CLASS_MEMBER_GUIEVENT_HANDLER(OnHandleMouseDown, vl::presentation::compositions::GuiMouseEventArgs)
				CLASS_MEMBER_GUIEVENT_HANDLER(OnHandleMouseMove, vl::presentation::compositions::GuiMouseEventArgs)
				CLASS_MEMBER_GUIEVENT_HANDLER(OnHandleMouseUp, vl::presentation::compositions::GuiMouseEventArgs)
			END_CLASS_MEMBER(demos::HTrackerTemplate)

			BEGIN_CLASS_MEMBER(demos::ItemBackgroundTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiSelectableButtonTemplate)
				CLASS_MEMBER_CONSTRUCTOR(demos::ItemBackgroundTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(demos::ItemBackgroundTemplate)

			BEGIN_CLASS_MEMBER(demos::LabelTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiLabelTemplate)
				CLASS_MEMBER_CONSTRUCTOR(demos::LabelTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(demos::LabelTemplate)

			BEGIN_CLASS_MEMBER(demos::LeftScrollButtonTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiButtonTemplate)
				CLASS_MEMBER_CONSTRUCTOR(demos::LeftScrollButtonTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(demos::LeftScrollButtonTemplate)

			BEGIN_CLASS_MEMBER(demos::ListViewColumnHeaderTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiListViewColumnHeaderTemplate)
				CLASS_MEMBER_CONSTRUCTOR(demos::ListViewColumnHeaderTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(demos::ListViewColumnHeaderTemplate)

			BEGIN_CLASS_MEMBER(demos::ListViewTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiListViewTemplate)
				CLASS_MEMBER_CONSTRUCTOR(demos::ListViewTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(demos::ListViewTemplate)

			BEGIN_CLASS_MEMBER(demos::MainWindow)
				CLASS_MEMBER_BASE(vl::presentation::controls::GuiWindow)
				CLASS_MEMBER_CONSTRUCTOR(demos::MainWindow*(), NO_PARAMETER)
			END_CLASS_MEMBER(demos::MainWindow)

			BEGIN_CLASS_MEMBER(demos::MenuBarButtonTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiToolstripButtonTemplate)
				CLASS_MEMBER_CONSTRUCTOR(demos::MenuBarButtonTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(demos::MenuBarButtonTemplate)

			BEGIN_CLASS_MEMBER(demos::MenuItemButtonTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiToolstripButtonTemplate)
				CLASS_MEMBER_CONSTRUCTOR(demos::MenuItemButtonTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(demos::MenuItemButtonTemplate)

			BEGIN_CLASS_MEMBER(demos::MenuSplitterTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiControlTemplate)
				CLASS_MEMBER_CONSTRUCTOR(demos::MenuSplitterTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(demos::MenuSplitterTemplate)

			BEGIN_CLASS_MEMBER(demos::MultilineTextBoxTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiMultilineTextBoxTemplate)
				CLASS_MEMBER_CONSTRUCTOR(demos::MultilineTextBoxTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(demos::MultilineTextBoxTemplate)

			BEGIN_CLASS_MEMBER(demos::ProgressBarTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiScrollTemplate)
				CLASS_MEMBER_CONSTRUCTOR(demos::ProgressBarTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(demos::ProgressBarTemplate)

			BEGIN_CLASS_MEMBER(demos::RadioButtonTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiSelectableButtonTemplate)
				CLASS_MEMBER_CONSTRUCTOR(demos::RadioButtonTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(demos::RadioButtonTemplate)

			BEGIN_CLASS_MEMBER(demos::RadioTextListTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiTextListTemplate)
				CLASS_MEMBER_CONSTRUCTOR(demos::RadioTextListTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(demos::RadioTextListTemplate)

			BEGIN_CLASS_MEMBER(demos::RightScrollButtonTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiButtonTemplate)
				CLASS_MEMBER_CONSTRUCTOR(demos::RightScrollButtonTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(demos::RightScrollButtonTemplate)

			BEGIN_CLASS_MEMBER(demos::ScrollViewTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiScrollViewTemplate)
				CLASS_MEMBER_CONSTRUCTOR(demos::ScrollViewTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(demos::ScrollViewTemplate)

			BEGIN_CLASS_MEMBER(demos::SinglelineTextBoxTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiSinglelineTextBoxTemplate)
				CLASS_MEMBER_CONSTRUCTOR(demos::SinglelineTextBoxTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(demos::SinglelineTextBoxTemplate)

			BEGIN_CLASS_MEMBER(demos::TabDropdownTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiButtonTemplate)
				CLASS_MEMBER_CONSTRUCTOR(demos::TabDropdownTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(demos::TabDropdownTemplate)

			BEGIN_CLASS_MEMBER(demos::TabHeaderTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiSelectableButtonTemplate)
				CLASS_MEMBER_CONSTRUCTOR(demos::TabHeaderTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(demos::TabHeaderTemplate)

			BEGIN_CLASS_MEMBER(demos::TabTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiTabTemplate)
				CLASS_MEMBER_CONSTRUCTOR(demos::TabTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(demos::TabTemplate)

			BEGIN_CLASS_MEMBER(demos::TextListTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiTextListTemplate)
				CLASS_MEMBER_CONSTRUCTOR(demos::TextListTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(demos::TextListTemplate)

			BEGIN_CLASS_MEMBER(demos::ToolstripButtonTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiToolstripButtonTemplate)
				CLASS_MEMBER_CONSTRUCTOR(demos::ToolstripButtonTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(demos::ToolstripButtonTemplate)

			BEGIN_CLASS_MEMBER(demos::ToolstripDropdownButtonTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiToolstripButtonTemplate)
				CLASS_MEMBER_CONSTRUCTOR(demos::ToolstripDropdownButtonTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(demos::ToolstripDropdownButtonTemplate)

			BEGIN_CLASS_MEMBER(demos::ToolstripMenuTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiMenuTemplate)
				CLASS_MEMBER_CONSTRUCTOR(demos::ToolstripMenuTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(demos::ToolstripMenuTemplate)

			BEGIN_CLASS_MEMBER(demos::ToolstripSplitArrowTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiSelectableButtonTemplate)
				CLASS_MEMBER_CONSTRUCTOR(demos::ToolstripSplitArrowTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(demos::ToolstripSplitArrowTemplate)

			BEGIN_CLASS_MEMBER(demos::ToolstripSplitButtonTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiToolstripButtonTemplate)
				CLASS_MEMBER_CONSTRUCTOR(demos::ToolstripSplitButtonTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(demos::ToolstripSplitButtonTemplate)

			BEGIN_CLASS_MEMBER(demos::ToolstripSplitterTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiControlTemplate)
				CLASS_MEMBER_CONSTRUCTOR(demos::ToolstripSplitterTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(demos::ToolstripSplitterTemplate)

			BEGIN_CLASS_MEMBER(demos::ToolstripTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiControlTemplate)
				CLASS_MEMBER_CONSTRUCTOR(demos::ToolstripTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(demos::ToolstripTemplate)

			BEGIN_CLASS_MEMBER(demos::TooltipTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiWindowTemplate)
				CLASS_MEMBER_CONSTRUCTOR(demos::TooltipTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(demos::TooltipTemplate)

			BEGIN_CLASS_MEMBER(demos::TopScrollButtonTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiButtonTemplate)
				CLASS_MEMBER_CONSTRUCTOR(demos::TopScrollButtonTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(demos::TopScrollButtonTemplate)

			BEGIN_CLASS_MEMBER(demos::TreeViewTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiTreeViewTemplate)
				CLASS_MEMBER_CONSTRUCTOR(demos::TreeViewTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(demos::TreeViewTemplate)

			BEGIN_CLASS_MEMBER(demos::VScrollHandleTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiButtonTemplate)
				CLASS_MEMBER_CONSTRUCTOR(demos::VScrollHandleTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(demos::VScrollHandleTemplate)

			BEGIN_CLASS_MEMBER(demos::VScrollTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiScrollTemplate)
				CLASS_MEMBER_CONSTRUCTOR(demos::VScrollTemplate*(), NO_PARAMETER)

				CLASS_MEMBER_GUIEVENT_HANDLER(OnHandleMouseDown, vl::presentation::compositions::GuiMouseEventArgs)
				CLASS_MEMBER_GUIEVENT_HANDLER(OnHandleMouseMove, vl::presentation::compositions::GuiMouseEventArgs)
				CLASS_MEMBER_GUIEVENT_HANDLER(OnHandleMouseUp, vl::presentation::compositions::GuiMouseEventArgs)
			END_CLASS_MEMBER(demos::VScrollTemplate)

			BEGIN_CLASS_MEMBER(demos::VTrackerTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiScrollTemplate)
				CLASS_MEMBER_CONSTRUCTOR(demos::VTrackerTemplate*(), NO_PARAMETER)

				CLASS_MEMBER_GUIEVENT_HANDLER(OnHandleMouseDown, vl::presentation::compositions::GuiMouseEventArgs)
				CLASS_MEMBER_GUIEVENT_HANDLER(OnHandleMouseMove, vl::presentation::compositions::GuiMouseEventArgs)
				CLASS_MEMBER_GUIEVENT_HANDLER(OnHandleMouseUp, vl::presentation::compositions::GuiMouseEventArgs)
			END_CLASS_MEMBER(demos::VTrackerTemplate)

			BEGIN_CLASS_MEMBER(demos::WindowTemplate)
				CLASS_MEMBER_BASE(vl::presentation::templates::GuiWindowTemplate)
				CLASS_MEMBER_CONSTRUCTOR(demos::WindowTemplate*(), NO_PARAMETER)
			END_CLASS_MEMBER(demos::WindowTemplate)

			#undef _

			class HelloWorldResourceLoader : public Object, public ITypeLoader
			{
			public:
				void Load(ITypeManager* manager)
				{
					ADD_TYPE_INFO(demos::BottomScrollButtonTemplate)
					ADD_TYPE_INFO(demos::ButtonTemplate)
					ADD_TYPE_INFO(demos::CheckBoxTemplate)
					ADD_TYPE_INFO(demos::CheckItemBackgroundTemplate)
					ADD_TYPE_INFO(demos::CheckTextListTemplate)
					ADD_TYPE_INFO(demos::ComboBoxTemplate)
					ADD_TYPE_INFO(demos::DatePickerTemplate)
					ADD_TYPE_INFO(demos::DocumentLabelTemplate)
					ADD_TYPE_INFO(demos::ExpandingDecoratorTemplate)
					ADD_TYPE_INFO(demos::GroupBoxTemplate)
					ADD_TYPE_INFO(demos::HScrollHandleTemplate)
					ADD_TYPE_INFO(demos::HScrollTemplate)
					ADD_TYPE_INFO(demos::HTrackerTemplate)
					ADD_TYPE_INFO(demos::ItemBackgroundTemplate)
					ADD_TYPE_INFO(demos::LabelTemplate)
					ADD_TYPE_INFO(demos::LeftScrollButtonTemplate)
					ADD_TYPE_INFO(demos::ListViewColumnHeaderTemplate)
					ADD_TYPE_INFO(demos::ListViewTemplate)
					ADD_TYPE_INFO(demos::MainWindow)
					ADD_TYPE_INFO(demos::MenuBarButtonTemplate)
					ADD_TYPE_INFO(demos::MenuItemButtonTemplate)
					ADD_TYPE_INFO(demos::MenuSplitterTemplate)
					ADD_TYPE_INFO(demos::MultilineTextBoxTemplate)
					ADD_TYPE_INFO(demos::ProgressBarTemplate)
					ADD_TYPE_INFO(demos::RadioButtonTemplate)
					ADD_TYPE_INFO(demos::RadioTextListTemplate)
					ADD_TYPE_INFO(demos::RightScrollButtonTemplate)
					ADD_TYPE_INFO(demos::ScrollViewTemplate)
					ADD_TYPE_INFO(demos::SinglelineTextBoxTemplate)
					ADD_TYPE_INFO(demos::TabDropdownTemplate)
					ADD_TYPE_INFO(demos::TabHeaderTemplate)
					ADD_TYPE_INFO(demos::TabTemplate)
					ADD_TYPE_INFO(demos::TextListTemplate)
					ADD_TYPE_INFO(demos::ToolstripButtonTemplate)
					ADD_TYPE_INFO(demos::ToolstripDropdownButtonTemplate)
					ADD_TYPE_INFO(demos::ToolstripMenuTemplate)
					ADD_TYPE_INFO(demos::ToolstripSplitArrowTemplate)
					ADD_TYPE_INFO(demos::ToolstripSplitButtonTemplate)
					ADD_TYPE_INFO(demos::ToolstripSplitterTemplate)
					ADD_TYPE_INFO(demos::ToolstripTemplate)
					ADD_TYPE_INFO(demos::TooltipTemplate)
					ADD_TYPE_INFO(demos::TopScrollButtonTemplate)
					ADD_TYPE_INFO(demos::TreeViewTemplate)
					ADD_TYPE_INFO(demos::VScrollHandleTemplate)
					ADD_TYPE_INFO(demos::VScrollTemplate)
					ADD_TYPE_INFO(demos::VTrackerTemplate)
					ADD_TYPE_INFO(demos::WindowTemplate)
				}

				void Unload(ITypeManager* manager)
				{
				}
			};

			class HelloWorldResourcePlugin : public Object, public vl::presentation::controls::IGuiPlugin
			{
			public:
				void Load()override
				{
					GetGlobalTypeManager()->AddTypeLoader(new HelloWorldResourceLoader);
				}

				void AfterLoad()override
				{
				}

				void Unload()override
				{
				}
			};
			GUI_REGISTER_PLUGIN(HelloWorldResourcePlugin)
		}
	}
}

