/***********************************************************************
Vczh Library++ 3.0
Developer: Zihan Chen(vczh)
GacUI::HelloWorld

This file is generated by: Vczh GacUI Resource Code Generator
************************************************************************
DO NOT MODIFY
***********************************************************************/

#ifndef VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld
#define VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld

#include "HScrollTemplate.h"
#include "HTrackerTemplate.h"
#include "VScrollTemplate.h"
#include "VTrackerTemplate.h"
#include "MainWindow.h"

#endif
