/***********************************************************************
Vczh Library++ 3.0
Developer: Zihan Chen(vczh)
GacUI::HelloWorld

This file is generated by: Vczh GacUI Resource Code Generator
************************************************************************
DO NOT MODIFY
***********************************************************************/

#ifndef VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld
#define VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld

#include "BottomScrollButtonTemplate.h"
#include "ButtonTemplate.h"
#include "CheckBoxTemplate.h"
#include "CheckItemBackgroundTemplate.h"
#include "CheckTextListTemplate.h"
#include "ComboBoxTemplate.h"
#include "DatePickerTemplate.h"
#include "DocumentLabelTemplate.h"
#include "ExpandingDecoratorTemplate.h"
#include "GroupBoxTemplate.h"
#include "HScrollHandleTemplate.h"
#include "HScrollTemplate.h"
#include "HTrackerTemplate.h"
#include "ItemBackgroundTemplate.h"
#include "LabelTemplate.h"
#include "LeftScrollButtonTemplate.h"
#include "ListViewColumnHeaderTemplate.h"
#include "ListViewTemplate.h"
#include "MainWindow.h"
#include "MenuBarButtonTemplate.h"
#include "MenuItemButtonTemplate.h"
#include "MenuSplitterTemplate.h"
#include "MultilineTextBoxTemplate.h"
#include "ProgressBarTemplate.h"
#include "RadioButtonTemplate.h"
#include "RadioTextListTemplate.h"
#include "RightScrollButtonTemplate.h"
#include "ScrollViewTemplate.h"
#include "SinglelineTextBoxTemplate.h"
#include "TabDropdownTemplate.h"
#include "TabHeaderTemplate.h"
#include "TabTemplate.h"
#include "TextListTemplate.h"
#include "ToolstripButtonTemplate.h"
#include "ToolstripDropdownButtonTemplate.h"
#include "ToolstripMenuTemplate.h"
#include "ToolstripSplitArrowTemplate.h"
#include "ToolstripSplitButtonTemplate.h"
#include "ToolstripSplitterTemplate.h"
#include "ToolstripTemplate.h"
#include "TopScrollButtonTemplate.h"
#include "TreeViewTemplate.h"
#include "VScrollHandleTemplate.h"
#include "VScrollTemplate.h"
#include "VTrackerTemplate.h"
#include "WindowTemplate.h"

#endif
