/***********************************************************************
Vczh Library++ 3.0
Developer: Zihan Chen(vczh)
GacUI::HScrollHandleTemplate

This file is generated by: Vczh GacUI Resource Code Generator
***********************************************************************/

#ifndef VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_HScrollHandleTemplate
#define VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_HScrollHandleTemplate

#include "HelloWorldPartialClasses.h"

namespace demos
{
	class HScrollHandleTemplate : public HScrollHandleTemplate_<HScrollHandleTemplate>
	{
		friend class HScrollHandleTemplate_<HScrollHandleTemplate>;
		friend struct vl::reflection::description::CustomTypeDescriptorSelector<HScrollHandleTemplate>;
	protected:

		// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)
		// #endregion CLASS_MEMBER_GUIEVENT_HANDLER
	public:
		HScrollHandleTemplate();
	};
}

#endif
