/***********************************************************************
Vczh Library++ 3.0
Developer: Zihan Chen(vczh)
GacUI::HTrackerTemplate

This file is generated by: Vczh GacUI Resource Code Generator
***********************************************************************/

#ifndef VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_HTrackerTemplate
#define VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_HTrackerTemplate

#include "HelloWorldPartialClasses.h"

namespace darkskin
{
	class HTrackerTemplate : public HTrackerTemplate_<HTrackerTemplate>
	{
		friend class HTrackerTemplate_<HTrackerTemplate>;
		friend struct vl::reflection::description::CustomTypeDescriptorSelector<HTrackerTemplate>;
	protected:
		Point								draggingStartLocation;
		bool								draggingHandle = false;

		// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)
		void OnHandleMouseDown(GuiGraphicsComposition* sender, vl::presentation::compositions::GuiMouseEventArgs& arguments);
		void OnHandleMouseMove(GuiGraphicsComposition* sender, vl::presentation::compositions::GuiMouseEventArgs& arguments);
		void OnHandleMouseUp(GuiGraphicsComposition* sender, vl::presentation::compositions::GuiMouseEventArgs& arguments);
		// #endregion CLASS_MEMBER_GUIEVENT_HANDLER
	public:
		HTrackerTemplate();
	};
}

#endif
