/***********************************************************************
Vczh Library++ 3.0
Developer: Zihan Chen(vczh)
GacUI::ItemBackgroundTemplate

This file is generated by: Vczh GacUI Resource Code Generator
***********************************************************************/

#ifndef VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_ItemBackgroundTemplate
#define VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_ItemBackgroundTemplate

#include "HelloWorldPartialClasses.h"

namespace demos
{
	class ItemBackgroundTemplate : public ItemBackgroundTemplate_<ItemBackgroundTemplate>
	{
		friend class ItemBackgroundTemplate_<ItemBackgroundTemplate>;
		friend struct vl::reflection::description::CustomTypeDescriptorSelector<ItemBackgroundTemplate>;
	protected:

		// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)
		// #endregion CLASS_MEMBER_GUIEVENT_HANDLER
	public:
		ItemBackgroundTemplate();
	};
}

#endif
