/***********************************************************************
Vczh Library++ 3.0
Developer: Zihan Chen(vczh)
GacUI::LabelTemplate

This file is generated by: Vczh GacUI Resource Code Generator
***********************************************************************/

#ifndef VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_LabelTemplate
#define VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_LabelTemplate

#include "HelloWorldPartialClasses.h"

namespace demos
{
	class LabelTemplate : public LabelTemplate_<LabelTemplate>
	{
		friend class LabelTemplate_<LabelTemplate>;
		friend struct vl::reflection::description::CustomTypeDescriptorSelector<LabelTemplate>;
	protected:

		// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)
		// #endregion CLASS_MEMBER_GUIEVENT_HANDLER
	public:
		LabelTemplate();
	};
}

#endif
