/***********************************************************************
Vczh Library++ 3.0
Developer: Zihan Chen(vczh)
GacUI::LeftScrollButtonTemplate

This file is generated by: Vczh GacUI Resource Code Generator
***********************************************************************/

#ifndef VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_LeftScrollButtonTemplate
#define VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_LeftScrollButtonTemplate

#include "HelloWorldPartialClasses.h"

namespace demos
{
	class LeftScrollButtonTemplate : public LeftScrollButtonTemplate_<LeftScrollButtonTemplate>
	{
		friend class LeftScrollButtonTemplate_<LeftScrollButtonTemplate>;
		friend struct vl::reflection::description::CustomTypeDescriptorSelector<LeftScrollButtonTemplate>;
	protected:

		// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)
		// #endregion CLASS_MEMBER_GUIEVENT_HANDLER
	public:
		LeftScrollButtonTemplate();
	};
}

#endif
