/***********************************************************************
Vczh Library++ 3.0
Developer: Zihan Chen(vczh)
GacUI::ListViewTemplate

This file is generated by: Vczh GacUI Resource Code Generator
***********************************************************************/

#ifndef VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_ListViewTemplate
#define VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_ListViewTemplate

#include "HelloWorldPartialClasses.h"

namespace demos
{
	class ListViewTemplate : public ListViewTemplate_<ListViewTemplate>
	{
		friend class ListViewTemplate_<ListViewTemplate>;
		friend struct vl::reflection::description::CustomTypeDescriptorSelector<ListViewTemplate>;
	protected:

		// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)
		// #endregion CLASS_MEMBER_GUIEVENT_HANDLER
	public:
		ListViewTemplate();
	};
}

#endif
