/***********************************************************************
Vczh Library++ 3.0
Developer: Zihan Chen(vczh)
GacUI::ListViewColumnHeaderTemplate

This file is generated by: Vczh GacUI Resource Code Generator
***********************************************************************/

#ifndef VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_ListViewColumnHeaderTemplate
#define VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_ListViewColumnHeaderTemplate

#include "HelloWorldPartialClasses.h"

namespace demos
{
	class ListViewColumnHeaderTemplate : public ListViewColumnHeaderTemplate_<ListViewColumnHeaderTemplate>
	{
		friend class ListViewColumnHeaderTemplate_<ListViewColumnHeaderTemplate>;
		friend struct vl::reflection::description::CustomTypeDescriptorSelector<ListViewColumnHeaderTemplate>;
	protected:

		// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)
		// #endregion CLASS_MEMBER_GUIEVENT_HANDLER
	public:
		ListViewColumnHeaderTemplate();
	};
}

#endif
