/***********************************************************************
Vczh Library++ 3.0
Developer: Zihan Chen(vczh)
GacUI::MenuBarButtonTemplate

This file is generated by: Vczh GacUI Resource Code Generator
***********************************************************************/

#ifndef VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_MenuBarButtonTemplate
#define VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_MenuBarButtonTemplate

#include "HelloWorldPartialClasses.h"

namespace demos
{
	class MenuBarButtonTemplate : public MenuBarButtonTemplate_<MenuBarButtonTemplate>
	{
		friend class MenuBarButtonTemplate_<MenuBarButtonTemplate>;
		friend struct vl::reflection::description::CustomTypeDescriptorSelector<MenuBarButtonTemplate>;
	protected:

		// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)
		// #endregion CLASS_MEMBER_GUIEVENT_HANDLER
	public:
		MenuBarButtonTemplate();
	};
}

#endif
