/***********************************************************************
Vczh Library++ 3.0
Developer: Zihan Chen(vczh)
GacUI::MenuItemButtonTemplate

This file is generated by: Vczh GacUI Resource Code Generator
***********************************************************************/

#ifndef VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_MenuItemButtonTemplate
#define VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_MenuItemButtonTemplate

#include "HelloWorldPartialClasses.h"

namespace demos
{
	class MenuItemButtonTemplate : public MenuItemButtonTemplate_<MenuItemButtonTemplate>
	{
		friend class MenuItemButtonTemplate_<MenuItemButtonTemplate>;
		friend struct vl::reflection::description::CustomTypeDescriptorSelector<MenuItemButtonTemplate>;
	protected:

		// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)
		// #endregion CLASS_MEMBER_GUIEVENT_HANDLER
	public:
		MenuItemButtonTemplate();
	};
}

#endif
