/***********************************************************************
Vczh Library++ 3.0
Developer: Zihan Chen(vczh)
GacUI::MenuSplitterTemplate

This file is generated by: Vczh GacUI Resource Code Generator
***********************************************************************/

#ifndef VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_MenuSplitterTemplate
#define VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_MenuSplitterTemplate

#include "HelloWorldPartialClasses.h"

namespace demos
{
	class MenuSplitterTemplate : public MenuSplitterTemplate_<MenuSplitterTemplate>
	{
		friend class MenuSplitterTemplate_<MenuSplitterTemplate>;
		friend struct vl::reflection::description::CustomTypeDescriptorSelector<MenuSplitterTemplate>;
	protected:

		// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)
		// #endregion CLASS_MEMBER_GUIEVENT_HANDLER
	public:
		MenuSplitterTemplate();
	};
}

#endif
