/***********************************************************************
Vczh Library++ 3.0
Developer: Zihan Chen(vczh)
GacUI::MultilineTextBoxTemplate

This file is generated by: Vczh GacUI Resource Code Generator
***********************************************************************/

#ifndef VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_MultilineTextBoxTemplate
#define VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_MultilineTextBoxTemplate

#include "HelloWorldPartialClasses.h"

namespace demos
{
	class MultilineTextBoxTemplate : public MultilineTextBoxTemplate_<MultilineTextBoxTemplate>
	{
		friend class MultilineTextBoxTemplate_<MultilineTextBoxTemplate>;
		friend struct vl::reflection::description::CustomTypeDescriptorSelector<MultilineTextBoxTemplate>;
	protected:

		// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)
		// #endregion CLASS_MEMBER_GUIEVENT_HANDLER
	public:
		MultilineTextBoxTemplate();
	};
}

#endif
