/***********************************************************************
Vczh Library++ 3.0
Developer: Zihan Chen(vczh)
GacUI::ProgressBarTemplate

This file is generated by: Vczh GacUI Resource Code Generator
***********************************************************************/

#ifndef VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_ProgressBarTemplate
#define VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_ProgressBarTemplate

#include "HelloWorldPartialClasses.h"

namespace demos
{
	class ProgressBarTemplate : public ProgressBarTemplate_<ProgressBarTemplate>
	{
		friend class ProgressBarTemplate_<ProgressBarTemplate>;
		friend struct vl::reflection::description::CustomTypeDescriptorSelector<ProgressBarTemplate>;
	protected:

		// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)
		// #endregion CLASS_MEMBER_GUIEVENT_HANDLER
	public:
		ProgressBarTemplate();
	};
}

#endif
