/***********************************************************************
Vczh Library++ 3.0
Developer: Zihan Chen(vczh)
GacUI::RadioTextListTemplate

This file is generated by: Vczh GacUI Resource Code Generator
***********************************************************************/

#ifndef VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_RadioTextListTemplate
#define VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_RadioTextListTemplate

#include "HelloWorldPartialClasses.h"

namespace demos
{
	class RadioTextListTemplate : public RadioTextListTemplate_<RadioTextListTemplate>
	{
		friend class RadioTextListTemplate_<RadioTextListTemplate>;
		friend struct vl::reflection::description::CustomTypeDescriptorSelector<RadioTextListTemplate>;
	protected:

		// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)
		// #endregion CLASS_MEMBER_GUIEVENT_HANDLER
	public:
		RadioTextListTemplate();
	};
}

#endif
