/***********************************************************************
Vczh Library++ 3.0
Developer: Zihan Chen(vczh)
GacUI::RadioButtonTemplate

This file is generated by: Vczh GacUI Resource Code Generator
***********************************************************************/

#ifndef VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_RadioButtonTemplate
#define VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_RadioButtonTemplate

#include "HelloWorldPartialClasses.h"

namespace demos
{
	class RadioButtonTemplate : public RadioButtonTemplate_<RadioButtonTemplate>
	{
		friend class RadioButtonTemplate_<RadioButtonTemplate>;
		friend struct vl::reflection::description::CustomTypeDescriptorSelector<RadioButtonTemplate>;
	protected:

		// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)
		// #endregion CLASS_MEMBER_GUIEVENT_HANDLER
	public:
		RadioButtonTemplate();
	};
}

#endif
