/***********************************************************************
Vczh Library++ 3.0
Developer: Zihan Chen(vczh)
GacUI::RightScrollButtonTemplate

This file is generated by: Vczh GacUI Resource Code Generator
***********************************************************************/

#ifndef VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_RightScrollButtonTemplate
#define VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_RightScrollButtonTemplate

#include "HelloWorldPartialClasses.h"

namespace demos
{
	class RightScrollButtonTemplate : public RightScrollButtonTemplate_<RightScrollButtonTemplate>
	{
		friend class RightScrollButtonTemplate_<RightScrollButtonTemplate>;
		friend struct vl::reflection::description::CustomTypeDescriptorSelector<RightScrollButtonTemplate>;
	protected:

		// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)
		// #endregion CLASS_MEMBER_GUIEVENT_HANDLER
	public:
		RightScrollButtonTemplate();
	};
}

#endif
