/***********************************************************************
Vczh Library++ 3.0
Developer: Zihan Chen(vczh)
GacUI::ScrollViewTemplate

This file is generated by: Vczh GacUI Resource Code Generator
***********************************************************************/

#ifndef VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_ScrollViewTemplate
#define VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_ScrollViewTemplate

#include "HelloWorldPartialClasses.h"

namespace demos
{
	class ScrollViewTemplate : public ScrollViewTemplate_<ScrollViewTemplate>
	{
		friend class ScrollViewTemplate_<ScrollViewTemplate>;
		friend struct vl::reflection::description::CustomTypeDescriptorSelector<ScrollViewTemplate>;
	protected:

		// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)
		// #endregion CLASS_MEMBER_GUIEVENT_HANDLER
	public:
		ScrollViewTemplate();
	};
}

#endif
