/***********************************************************************
Vczh Library++ 3.0
Developer: Zihan Chen(vczh)
GacUI::SinglelineTextBoxTemplate

This file is generated by: Vczh GacUI Resource Code Generator
***********************************************************************/

#ifndef VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_SinglelineTextBoxTemplate
#define VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_SinglelineTextBoxTemplate

#include "HelloWorldPartialClasses.h"

namespace demos
{
	class SinglelineTextBoxTemplate : public SinglelineTextBoxTemplate_<SinglelineTextBoxTemplate>
	{
		friend class SinglelineTextBoxTemplate_<SinglelineTextBoxTemplate>;
		friend struct vl::reflection::description::CustomTypeDescriptorSelector<SinglelineTextBoxTemplate>;
	protected:

		// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)
		// #endregion CLASS_MEMBER_GUIEVENT_HANDLER
	public:
		SinglelineTextBoxTemplate();
	};
}

#endif
