/***********************************************************************
Vczh Library++ 3.0
Developer: Zihan Chen(vczh)
GacUI::TabDropdownTemplate

This file is generated by: Vczh GacUI Resource Code Generator
***********************************************************************/

#ifndef VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_TabDropdownTemplate
#define VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_TabDropdownTemplate

#include "HelloWorldPartialClasses.h"

namespace demos
{
	class TabDropdownTemplate : public TabDropdownTemplate_<TabDropdownTemplate>
	{
		friend class TabDropdownTemplate_<TabDropdownTemplate>;
		friend struct vl::reflection::description::CustomTypeDescriptorSelector<TabDropdownTemplate>;
	protected:

		// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)
		// #endregion CLASS_MEMBER_GUIEVENT_HANDLER
	public:
		TabDropdownTemplate();
	};
}

#endif
