/***********************************************************************
Vczh Library++ 3.0
Developer: Zihan Chen(vczh)
GacUI::TabHeaderTemplate

This file is generated by: Vczh GacUI Resource Code Generator
***********************************************************************/

#ifndef VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_TabHeaderTemplate
#define VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_TabHeaderTemplate

#include "HelloWorldPartialClasses.h"

namespace demos
{
	class TabHeaderTemplate : public TabHeaderTemplate_<TabHeaderTemplate>
	{
		friend class TabHeaderTemplate_<TabHeaderTemplate>;
		friend struct vl::reflection::description::CustomTypeDescriptorSelector<TabHeaderTemplate>;
	protected:

		// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)
		// #endregion CLASS_MEMBER_GUIEVENT_HANDLER
	public:
		TabHeaderTemplate();
	};
}

#endif
