/***********************************************************************
Vczh Library++ 3.0
Developer: Zihan Chen(vczh)
GacUI::TabTemplate

This file is generated by: Vczh GacUI Resource Code Generator
***********************************************************************/

#ifndef VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_TabTemplate
#define VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_TabTemplate

#include "HelloWorldPartialClasses.h"

namespace demos
{
	class TabTemplate : public TabTemplate_<TabTemplate>
	{
		friend class TabTemplate_<TabTemplate>;
		friend struct vl::reflection::description::CustomTypeDescriptorSelector<TabTemplate>;
	protected:

		// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)
		// #endregion CLASS_MEMBER_GUIEVENT_HANDLER
	public:
		TabTemplate();
	};
}

#endif
