/***********************************************************************
Vczh Library++ 3.0
Developer: Zihan Chen(vczh)
GacUI::TextListTemplate

This file is generated by: Vczh GacUI Resource Code Generator
***********************************************************************/

#ifndef VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_TextListTemplate
#define VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_TextListTemplate

#include "HelloWorldPartialClasses.h"

namespace demos
{
	class TextListTemplate : public TextListTemplate_<TextListTemplate>
	{
		friend class TextListTemplate_<TextListTemplate>;
		friend struct vl::reflection::description::CustomTypeDescriptorSelector<TextListTemplate>;
	protected:

		// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)
		// #endregion CLASS_MEMBER_GUIEVENT_HANDLER
	public:
		TextListTemplate();
	};
}

#endif
