/***********************************************************************
Vczh Library++ 3.0
Developer: Zihan Chen(vczh)
GacUI::TooltipTemplate

This file is generated by: Vczh GacUI Resource Code Generator
***********************************************************************/

#ifndef VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_TooltipTemplate
#define VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_TooltipTemplate

#include "HelloWorldPartialClasses.h"

namespace demos
{
	class TooltipTemplate : public demos::TooltipTemplate_<demos::TooltipTemplate>
	{
		friend class demos::TooltipTemplate_<demos::TooltipTemplate>;
		friend struct vl::reflection::description::CustomTypeDescriptorSelector<demos::TooltipTemplate>;
	protected:

		// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)
		// #endregion CLASS_MEMBER_GUIEVENT_HANDLER
	public:
		TooltipTemplate();
	};
}

#endif
