/***********************************************************************
Vczh Library++ 3.0
Developer: Zihan Chen(vczh)
GacUI::ToolstripButtonTemplate

This file is generated by: Vczh GacUI Resource Code Generator
***********************************************************************/

#ifndef VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_ToolstripButtonTemplate
#define VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_ToolstripButtonTemplate

#include "HelloWorldPartialClasses.h"

namespace demos
{
	class ToolstripButtonTemplate : public ToolstripButtonTemplate_<ToolstripButtonTemplate>
	{
		friend class ToolstripButtonTemplate_<ToolstripButtonTemplate>;
		friend struct vl::reflection::description::CustomTypeDescriptorSelector<ToolstripButtonTemplate>;
	protected:

		// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)
		// #endregion CLASS_MEMBER_GUIEVENT_HANDLER
	public:
		ToolstripButtonTemplate();
	};
}

#endif
