/***********************************************************************
Vczh Library++ 3.0
Developer: Zihan Chen(vczh)
GacUI::ToolstripSplitterTemplate

This file is generated by: Vczh GacUI Resource Code Generator
***********************************************************************/

#include "HelloWorld.h"

namespace demos
{
	// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)

	// #endregion CLASS_MEMBER_GUIEVENT_HANDLER

	ToolstripSplitterTemplate::ToolstripSplitterTemplate()
	{
		InitializeComponents();
	}
}
