/***********************************************************************
Vczh Library++ 3.0
Developer: Zihan Chen(vczh)
GacUI::ToolstripSplitArrowTemplate

This file is generated by: Vczh GacUI Resource Code Generator
***********************************************************************/

#ifndef VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_ToolstripSplitArrowTemplate
#define VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_ToolstripSplitArrowTemplate

#include "HelloWorldPartialClasses.h"

namespace demos
{
	class ToolstripSplitArrowTemplate : public ToolstripSplitArrowTemplate_<ToolstripSplitArrowTemplate>
	{
		friend class ToolstripSplitArrowTemplate_<ToolstripSplitArrowTemplate>;
		friend struct vl::reflection::description::CustomTypeDescriptorSelector<ToolstripSplitArrowTemplate>;
	protected:

		// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)
		// #endregion CLASS_MEMBER_GUIEVENT_HANDLER
	public:
		ToolstripSplitArrowTemplate();
	};
}

#endif
