/***********************************************************************
Vczh Library++ 3.0
Developer: Zihan Chen(vczh)
GacUI::ToolstripTemplate

This file is generated by: Vczh GacUI Resource Code Generator
***********************************************************************/

#ifndef VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_ToolstripTemplate
#define VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_ToolstripTemplate

#include "HelloWorldPartialClasses.h"

namespace demos
{
	class ToolstripTemplate : public ToolstripTemplate_<ToolstripTemplate>
	{
		friend class ToolstripTemplate_<ToolstripTemplate>;
		friend struct vl::reflection::description::CustomTypeDescriptorSelector<ToolstripTemplate>;
	protected:

		// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)
		// #endregion CLASS_MEMBER_GUIEVENT_HANDLER
	public:
		ToolstripTemplate();
	};
}

#endif
