/***********************************************************************
Vczh Library++ 3.0
Developer: Zihan Chen(vczh)
GacUI::ToolstripSplitButtonTemplate

This file is generated by: Vczh GacUI Resource Code Generator
***********************************************************************/

#ifndef VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_ToolstripSplitButtonTemplate
#define VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_ToolstripSplitButtonTemplate

#include "HelloWorldPartialClasses.h"

namespace demos
{
	class ToolstripSplitButtonTemplate : public ToolstripSplitButtonTemplate_<ToolstripSplitButtonTemplate>
	{
		friend class ToolstripSplitButtonTemplate_<ToolstripSplitButtonTemplate>;
		friend struct vl::reflection::description::CustomTypeDescriptorSelector<ToolstripSplitButtonTemplate>;
	protected:

		// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)
		// #endregion CLASS_MEMBER_GUIEVENT_HANDLER
	public:
		ToolstripSplitButtonTemplate();
	};
}

#endif
