/***********************************************************************
Vczh Library++ 3.0
Developer: Zihan Chen(vczh)
GacUI::ToolstripMenuTemplate

This file is generated by: Vczh GacUI Resource Code Generator
***********************************************************************/

#ifndef VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_ToolstripMenuTemplate
#define VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_ToolstripMenuTemplate

#include "HelloWorldPartialClasses.h"

namespace demos
{
	class ToolstripMenuTemplate : public ToolstripMenuTemplate_<ToolstripMenuTemplate>
	{
		friend class ToolstripMenuTemplate_<ToolstripMenuTemplate>;
		friend struct vl::reflection::description::CustomTypeDescriptorSelector<ToolstripMenuTemplate>;
	protected:

		// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)
		// #endregion CLASS_MEMBER_GUIEVENT_HANDLER
	public:
		ToolstripMenuTemplate();
	};
}

#endif
