/***********************************************************************
Vczh Library++ 3.0
Developer: Zihan Chen(vczh)
GacUI::TopScrollButtonTemplate

This file is generated by: Vczh GacUI Resource Code Generator
***********************************************************************/

#ifndef VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_TopScrollButtonTemplate
#define VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_TopScrollButtonTemplate

#include "HelloWorldPartialClasses.h"

namespace demos
{
	class TopScrollButtonTemplate : public TopScrollButtonTemplate_<TopScrollButtonTemplate>
	{
		friend class TopScrollButtonTemplate_<TopScrollButtonTemplate>;
		friend struct vl::reflection::description::CustomTypeDescriptorSelector<TopScrollButtonTemplate>;
	protected:

		// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)
		// #endregion CLASS_MEMBER_GUIEVENT_HANDLER
	public:
		TopScrollButtonTemplate();
	};
}

#endif
