/***********************************************************************
Vczh Library++ 3.0
Developer: Zihan Chen(vczh)
GacUI::TreeViewTemplate

This file is generated by: Vczh GacUI Resource Code Generator
***********************************************************************/

#ifndef VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_TreeViewTemplate
#define VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_TreeViewTemplate

#include "HelloWorldPartialClasses.h"

namespace demos
{
	class TreeViewTemplate : public TreeViewTemplate_<TreeViewTemplate>
	{
		friend class TreeViewTemplate_<TreeViewTemplate>;
		friend struct vl::reflection::description::CustomTypeDescriptorSelector<TreeViewTemplate>;
	protected:

		// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)
		// #endregion CLASS_MEMBER_GUIEVENT_HANDLER
	public:
		TreeViewTemplate();
	};
}

#endif
