/***********************************************************************
Vczh Library++ 3.0
Developer: Zihan Chen(vczh)
GacUI::VScrollHandleTemplate

This file is generated by: Vczh GacUI Resource Code Generator
***********************************************************************/

#ifndef VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_VScrollHandleTemplate
#define VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_VScrollHandleTemplate

#include "HelloWorldPartialClasses.h"

namespace demos
{
	class VScrollHandleTemplate : public VScrollHandleTemplate_<VScrollHandleTemplate>
	{
		friend class VScrollHandleTemplate_<VScrollHandleTemplate>;
		friend struct vl::reflection::description::CustomTypeDescriptorSelector<VScrollHandleTemplate>;
	protected:

		// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)
		// #endregion CLASS_MEMBER_GUIEVENT_HANDLER
	public:
		VScrollHandleTemplate();
	};
}

#endif
