/***********************************************************************
Vczh Library++ 3.0
Developer: Zihan Chen(vczh)
GacUI::VTrackerTemplate

This file is generated by: Vczh GacUI Resource Code Generator
***********************************************************************/

#ifndef VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_VTrackerTemplate
#define VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_VTrackerTemplate

#include "HelloWorldPartialClasses.h"

namespace darkskin
{
	class VTrackerTemplate : public VTrackerTemplate_<VTrackerTemplate>
	{
		friend class VTrackerTemplate_<VTrackerTemplate>;
		friend struct vl::reflection::description::CustomTypeDescriptorSelector<VTrackerTemplate>;
	protected:

		Point								draggingStartLocation;
		bool								draggingHandle = false;

		// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)
		void OnHandleMouseDown(GuiGraphicsComposition* sender, vl::presentation::compositions::GuiMouseEventArgs& arguments);
		void OnHandleMouseMove(GuiGraphicsComposition* sender, vl::presentation::compositions::GuiMouseEventArgs& arguments);
		void OnHandleMouseUp(GuiGraphicsComposition* sender, vl::presentation::compositions::GuiMouseEventArgs& arguments);
		// #endregion CLASS_MEMBER_GUIEVENT_HANDLER
	public:
		VTrackerTemplate();
	};
}

#endif
