/***********************************************************************
Vczh Library++ 3.0
Developer: Zihan Chen(vczh)
GacUI::WindowTemplate

This file is generated by: Vczh GacUI Resource Code Generator
***********************************************************************/

#ifndef VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_WindowTemplate
#define VCZH_GACUI_RESOURCE_CODE_GENERATOR_HelloWorld_WindowTemplate

#include "HelloWorldPartialClasses.h"

namespace demos
{
	class WindowTemplate : public WindowTemplate_<WindowTemplate>
	{
		friend class WindowTemplate_<WindowTemplate>;
		friend struct vl::reflection::description::CustomTypeDescriptorSelector<WindowTemplate>;
	protected:

		// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)
		// #endregion CLASS_MEMBER_GUIEVENT_HANDLER
	public:
		WindowTemplate();
	};
}

#endif
