/***********************************************************************
Vczh Library++ 3.0
Developer: Zihan Chen(vczh)
GacUI::Partial Classes

This file is generated by: Vczh GacUI Resource Code Generator
************************************************************************
DO NOT MODIFY
***********************************************************************/

#ifndef VCZH_GACUI_RESOURCE_CODE_GENERATOR_Demo_PARTIAL_CLASSES
#define VCZH_GACUI_RESOURCE_CODE_GENERATOR_Demo_PARTIAL_CLASSES

#include "..\..\..\Public\Source\GacUIReflection.h"

namespace demos
{
	class ISeason;
	class IViewModel;
	class MainWindow;

	class ISeason : public virtual vl::reflection::IDescriptable, public vl::reflection::Description<ISeason>
	{
	public:

		virtual vl::WString GetSeason() = 0;

		virtual vl::WString GetDescription() = 0;

		virtual vl::Ptr<vl::reflection::description::IValueObservableList> GetChildren() = 0;
	};

	class IViewModel : public virtual vl::reflection::IDescriptable, public vl::reflection::Description<IViewModel>
	{
	public:

		virtual vl::Ptr<vl::reflection::description::IValueObservableList> GetSeasons() = 0;

		virtual vl::Ptr<vl::reflection::description::IValueObservableList> GetComplexSeasons() = 0;

		virtual vl::Ptr<demos::ISeason> GetTreeSeasons() = 0;

		virtual void AddSeason() = 0;
		virtual void AddComplexSeason() = 0;
		virtual void AddTreeSeason() = 0;
	};

	template<typename TImpl>
	class MainWindow_ : public vl::presentation::controls::GuiWindow, public vl::presentation::GuiInstancePartialClass<vl::presentation::controls::GuiWindow>, public vl::reflection::Description<TImpl>
	{
		friend struct vl::reflection::description::CustomTypeDescriptorSelector<TImpl>;
	private:
		Ptr<demos::IViewModel> ViewModel_;
	protected:
		vl::presentation::controls::GuiBindableTextList* listSeasons3;
		vl::presentation::controls::GuiBindableListView* listViewSeasons3;
		vl::presentation::controls::GuiBindableTreeView* treeViewSeasons3;

		void InitializeComponents(Ptr<demos::IViewModel> ViewModel)
		{
			ViewModel_ = ViewModel;
			if (InitializeFromResource())
			{
				GUI_INSTANCE_REFERENCE(listSeasons3);
				GUI_INSTANCE_REFERENCE(listViewSeasons3);
				GUI_INSTANCE_REFERENCE(treeViewSeasons3);
			}
			else
			{
				ViewModel_ = 0;
			}
		}
	public:
		MainWindow_()
			:vl::presentation::GuiInstancePartialClass<vl::presentation::controls::GuiWindow>(L"demos::MainWindow")
			,vl::presentation::controls::GuiWindow(vl::presentation::theme::GetCurrentTheme()->CreateWindowStyle())
			,listSeasons3(0)
			,listViewSeasons3(0)
			,treeViewSeasons3(0)
		{
		}

		Ptr<demos::IViewModel> GetViewModel()
		{
			return ViewModel_;
		}
	};

}
namespace vl
{
	namespace reflection
	{
		namespace description
		{
			DECL_TYPE_INFO(demos::ISeason)
			DECL_TYPE_INFO(demos::IViewModel)
			DECL_TYPE_INFO(demos::MainWindow)

		}
	}
}

#endif
