/***********************************************************************
Vczh Library++ 3.0
Developer: Zihan Chen(vczh)
GacUI::MainWindow

This file is generated by: Vczh GacUI Resource Code Generator
***********************************************************************/

#ifndef VCZH_GACUI_RESOURCE_CODE_GENERATOR_DataGridModel_MainWindow
#define VCZH_GACUI_RESOURCE_CODE_GENERATOR_DataGridModel_MainWindow

#include "DataGridModelPartialClasses.h"

namespace demos
{
	class MainWindow : public demos::MainWindow_<demos::MainWindow>
	{
		friend class demos::MainWindow_<demos::MainWindow>;
		friend struct vl::reflection::description::CustomTypeDescriptorSelector<demos::MainWindow>;
	protected:

		// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)
		// #endregion CLASS_MEMBER_GUIEVENT_HANDLER
	public:
		MainWindow(Ptr<demos::IDataGridModel> ViewModel);
	};
}

#endif
